title: Ashraf Alam

linkedin_username: ashrafalam
github_username:  ashrafalam
devto_username: ashrafalam
twitter_username: ashrafulalam
rss: rss

show_excerpts: true

minima:
  date_format: "%b %-d, %Y"

header_pages:
  - profile/awards.md
  - profile/talks.md
  - profile/profile.md
  - profile/connect.md

theme: minima 

plugins:
  - jekyll-feed
  - jekyll-seo-tag

