title: Ashraf Alam

show_excerpts: true

minima:
  date_format: "%b %-d, %Y"
  github: AshrafAlam

header_pages:
  - profile/awards.md
  - profile/talks.md
  - profile/profile.md
  - profile/connect.md

theme: minima 

plugins:
  - jekyll-feed
  - jekyll-seo-tag

